# Configuration for the supplied 42 CGI tester.

server {
    listen 127.0.0.1:8080;
    client_max_body_size 1000000000;

    location / {
        allow_methods GET;
        root /Users/batuhankiskac/Desktop/webserv/YoupiBanane;
        index youpi.bad_extension;
        autoindex off;
    }

    location /directory {
        allow_methods GET POST;
        root /Users/batuhankiskac/Desktop/webserv/YoupiBanane;
        index youpi.bad_extension;
        autoindex off;
        cgi_ext .bla;
        cgi_path /Users/batuhankiskac/Desktop/webserv/cgi_tester;
    }

    location /post_body {
        allow_methods POST;
        root /Users/batuhankiskac/Desktop/webserv;
        upload_enable on;
        upload_store /Users/batuhankiskac/Desktop/webserv/post_body;
        client_max_body_size 100;
    }
}
